---
name: Release docker image
on:
  push

jobs:
  release-docker:
    name: Release docker image
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ksatchit/test-k8s-app
          tag_with_ref: true
          add_git_labels: true
          tag_with_sha: true
